ITech-Fixers/vide-grenier-en-ligne

- App/Config.php
- App/Views/User/register.html
- Core/Model.php
- Dockerfile
- Injection dynamique de l'host docker pour setup la connexion à la base de données dynamiquement.
- Ajout des dépendances PHP manquantes.
> Fix : DB Config 

- App/Controllers/User.php
- App/Models/User.php
- App/Models/UserRegister.php
- App/Utility/Flash.php
- App/Views/User/login.html
- App/Views/User/register.html
- Core/Error.php
- Core/View.php
Fix : #5
Je n'ai pas encore réglé le problème du remember-me cookie, ce sera fait dans une PR séparée.
> Fix : Register & Login

- App/Controllers/User.php
- App/Models/User.php
- Core/Controller.php
Fix : #11
- Création d'une table `user_tokens` avec une clef étrangère sur l'id de la table `user`
- Ajout des méthodes de création du token dans le controller `User`
- Ajout des méthodes de création et suppression des tokens dans le model `User`
- Ajout de la vérification de la présence du remember-me cookie avant chaque action dans l'abstract controller de base
- Fix d'un oubli de vérification de la présence de l'user en BDD et gestion des erreurs en cas de mauvais mot de passe
> feature : ajout du cookie remember me

- App/Controllers/User.php
- App/Exception/UserNotFoundException.php
- App/Exception/ValidationException.php
- App/Views/User/login.html
- App/Views/User/register.html
Dans certains cas, les erreurs potentielles générées par le `login` et le `register` n'étaient pas remontées correctement et la redirection n'était pas bonne.
- Création d'exceptions personnalisées
- Déplacement des blocs try-catch dans les actions directement
> Fix : Gestion des exceptions au login et register

- App/Models/Cities.php
- App/Views/Product/Add.html
- App/Views/base.html
Fix : #23 
- Ajout du système d'autocomplete pour la sélection de la ville lors de l'ajout d'un article
- Vérification front que la ville a bien été sélectionner dans la liste de l'autocomplete.
- Ajout de jquery et jquery Ui pour rendre fonctionnel bootstrap-autocomplete
- Modification de l'api pour retourner l'ID et le nom réelle de la ville
> Fix systeme de séléction des villes

- App/Controllers/Api.php
- App/Controllers/Product.php
- App/Exception/CityNotFoundException.php
- App/Models/ArticleAdd.php
- App/Models/Articles.php
- App/Models/Cities.php
- App/Views/Product/Add.html
- App/Views/Product/Show.html
Fix : #25 
- Ajout des champs required en front.
- Mise à jour du script SQL pour inclure une clef étrangère vers la ville dans la table `article`.
- Mise à jour des requêtes de récupérations des produits pour afficher la ville.
- Affichage de la ville et du code postal dans la page `productShow`.
- Ajout de la méthode `getById()` dans le modèle `Article`.
- Ajout d'une classe de validation de la soumission d'un article.
- Ajout de la validation et de la gestion des erreurs dans le controller.
- Ajout d'exceptions personnalisées dans le cas où la ville soumise ne serait pas valide.
- Refactoring et nettoyage des fichiers impactés.
> Fix : Validation de la soumission d'un article

- App/Models/Articles.php
> Fix: nom du paramètre attendu pour le tri par date des articles

- App/Controllers/Product.php
- App/Exception/ArticleNotFoundException.php
- App/Exception/MailerException.php
- App/Models/Articles.php
- App/Models/ContactMessage.php
- App/Models/User.php
- App/Utility/Mailer.php
- App/Views/Product/Add.html
- App/Views/Product/Contact.html
- App/Views/Product/Show.html
- composer.json
- composer.lock
- docker-compose.yml
- public/index.php
Close: #29 
- Ajout des routes
- Ajout des actions correspondantes dans le controller
- Ajout de la page du formulaire de contact
- Ajout d'une colonne pour compter le nombre de contact pour un article
- Ajout d'une méthode pour retrouver un user en fonction d'un article
- Ajout de la lib [PHPMailer](https://github.com/PHPMailer/PHPMailer)
- Création d'un service Mailer
- Ajout de la correspondance des ports SMTP dans le docker-compose
- Ajout des exceptions personnalisées pour article non trouvé et le mailer
On sanitize le message avant de l'envoyer
> Ajout du formulaire de contact + envoi de mail

- App/Views/Product/Add.html
- App/Views/Product/Contact.html
Fix: #36 
Je n'ai jamais réussi à le centrer via `bootstrap`, c'est très bizarre, j'ai l'impression qu'il manque des classes. 
En attendant de fix ou même de mettre à jour `bootstrap` par une version plus récente, je passe un attribut style bien cochon directement sur l'attribut HTML pour centrer le formulaire.
> Centrage des formulaires contact + ajout d'article

- App/Controllers/Api.php
- App/Controllers/User.php
- App/Models/Articles.php
- App/Views/User/account.html
> Maj de la récuperation des articles d'un utilisateur dans l'espace compte via un call AJAX

- App/Views/Home/index.html
> Fix: icônes tri des articles

- App/Controllers/Api.php
- App/Models/Articles.php
- App/Views/Home/index.html
- App/Views/base.html
- public/swagger-ui/swagger.yaml
Close: #35 
- Récupération de la géolocalisation en `JS` via l'`API` du navigateur
- Sélection d'un radius de distance via un Slider `Bootstrap` (ajout de la lib `CSS+JS` en `cdn`)
- Maj de l'api pour gérer la récupération par géolocalisation
- Ajout d'une requête pour récupérer les articles "autour de moi" via la [Formule Haversine](https://fr.wikipedia.org/wiki/Formule_de_haversine)
- Mise à jour de la documentation `Openapi`
> Feature: Articles "autour de moi"

- App/Controllers/Api.php
- App/Models/Articles.php
- App/Views/Home/index.html
- App/Views/Product/Add.html
- App/Views/Product/Contact.html
- App/Views/base.html
- public/swagger-ui/swagger.yaml
Close: #54 
- Réaffichage de la barre de recherche
- Maj du template
- Inclusion du paramètre de la recherche dans le call API
- Maj de endpoint dans le controller de l'API pour gérer les différents cas
- Ajout de la méthode SQL de recherche dans le modèle (recherche dans le nom & la description de l'article)
- Maj de la documentation
> Feature: Recherche des articles

- App/Controllers/Api.php
- App/Controllers/Home.php
- App/Controllers/Statistics.php
- App/Controllers/User.php
- App/Models/Articles.php
- App/Models/Cities.php
- App/Models/User.php
- App/Service/Validation/ArticleAdd.php
- App/Service/Validation/ContactMessage.php
- App/Service/Validation/UserRegister.php
- App/Utility/Flash.php
- App/Utility/Hash.php
- App/Utility/Upload.php
- App/Views/Admin/Statistics.html
- Core/Controller.php
- Core/Model.php
- Core/Router.php
- public/index.php
> Typage et ajout des dockblocs manquants du back

- Dockerfile
- entrypoint.sh
Fix : #64 
- Ajout d'un `entrypoint.sh` pour exécuter les commandes une fois le container créer
> Fix Dockerfile

- App/Config.php
- App/Views/404.html
- App/Views/500.html
- Core/Router.php
- public/index.php
> Fix: Gestion des pages 404/500

- App/Views/Admin/Statistics.html
- App/Views/Home/index.html
- App/Views/Product/Add.html
- App/Views/Product/Contact.html
- App/Views/Product/Show.html
- App/Views/User/account.html
- App/Views/User/login.html
- App/Views/User/other.html
- App/Views/User/register.html
- App/Views/base.html
> Nettoyage et formatage des templates HTML

- App/Models/Articles.php
- App/Views/Home/index.html
Fix: #58 
Suppression des hashs et des sels de hash des mots de passes utilisateurs dans les réponses SQL
> Fix: Supression des secrets utilisateurs dans les réponses SQL

- App/Controllers/Product.php
- App/Exception/FileFormatException.php
- App/Utility/Upload.php
- App/Views/Product/Add.html
Fix: #57
- Ajout d'une méthode de vérification de l'extension du fichier uploadé pour l'image
- Déplacement de la vérification en amont de la persistance de l'article
- Ajout exceptions personnalisées
> Fix: Gestion des erreurs à l'upload de ficher

- App/Kernel.php
- Core/Controller.php
- Core/Error.php
- Core/Kernel.php
- Core/Model.php
- Core/Router.php
- Core/View.php
- public/index.php
Création d'une classe `Kernel` pour centraliser le fonctionnement de l'App
> Evol: Ajout d'une classe Kernel pour centraliser la config et le setup de l'Application
